import { Poppins } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import Footer from "@/components/Shared/Footer";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});
export const metadata = {
  title: "Mandiri ",
  description: "Generated by Singularity Limited",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className}>
      <body suppressHydrationWarning={true}>
        <div className="fixed  flex justify-center z-10 left-2 right-2">
          <Navbar />
        </div>
        {children}
        <div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
